
version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: legacybook-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: legacybook
      MYSQL_USER: legacyuser
      MYSQL_PASSWORD: legacy123
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
